[[redirects]]
  from = "/api/matches/*"
  to = "https://streamed.pk/api/matches/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/sports"
  to = "https://streamed.pk/api/sports"
  status = 200
  force = true

[[redirects]]
  from = "/api/stream/*"
  to = "https://streamed.pk/api/stream/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/images/*"
  to = "https://streamed.pk/api/images/:splat"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
